services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - CLIENT_ORIGIN=http://localhost:3001
    networks:
      - cars-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - cars-network

networks:
  cars-network:
    driver: bridge